### ISSUE TITLE
No paths found for XXXX_p_p

### ISSUE THREAD

**Issue by satomimitsuhashi** [christopher-vollmers/Mandalorion-old#1]
Hi
I have run this command;
python3 Mandalorion_just_align.py -f myfile.fastq -g GRCh37 -q 9

And then I got many these message.
No paths found for xxxxxxxxxxxxxxxxxx for approximately one third of the read.

And it finished with these message.

No paths found for eefdfdd6-0972-421d-94c1-26ba4c69286a_n_n
Processed 25220 queries in 19681.15 seconds (1.28 queries/sec)
Removed existing memory for shmid 425988
Removed existing memory for shmid 393219
Removed existing memory for shmid 360450
Removed existing memory for shmid 294912
Removed existing memory for shmid 327681
Traceback (most recent call last):
  File "Mandalorion_4_Align_Reads_With_Gmap.py", line 107, in <module>
    filter_reads(path,infile,outfile)
  File "Mandalorion_4_Align_Reads_With_Gmap.py", line 58, in filter_reads
    aligned_bases=sum(np.array(a[18].split(',')[:-1],dtype=int))/int(a[10])
IndexError: list index out of range

There are several output files but 2D_trimmed_l_filtered.fasta/fastq was empty.

If you could let me know what was wrong, that would be very helpful.

Thank you very much.

**Comment by christopher-vollmers** [comment]
If no path is found by gmap, the read is probably too low quality to align. I don't know enough about gmap to help you out with that. But it is expected to lose a bunch of reads at that step.

I am surprised your 2D_trimmed_l_filtered.fasta was empty. What about the .psl files gmap outputs?

Best,
Chris

**Comment by satomimitsuhashi** [comment]
Thank you for the reply! psl files were not empty.
I had 2.8G fasta file and got 2.6M of gmapoutput.psl and 1.6M of gmapoutput_filtered.psl.
Is it normal?

By the way, have you ever used any other aligner than gmap?

best,
Satomi

**Comment by christopher-vollmers** [comment]
That seems very low.
What kind of sample/genome are you trying to align?

We are bouncing back and forth between gmap and blat. gmap is faster and
introduces more mismatches while blat is much slower and introduces gaps
into alignments. I don't think any of these aligners is superior to the
other but unless split up your data and run many instances of blat it going
to take weeks to align the amount of data you have...

Cheers,
Chris

On Mon, Sep 11, 2017 at 10:37 PM, satomimitsuhashi <notifications@github.com

**Comment by satomimitsuhashi** [comment]
Dear Chris,

I am trying to sequence cDNA from human skeletal muscle using R9.5 flow cell and 1D^2 kit.
The reads were unexpectedly short in this run. There might be something wrong during the library preparation.

I have a better size .pls file (550M) mapped by LAST. 
Do you think I can switch to this .psl file from gmap .psl file, then run Manalorion_define_and_quantify_isoforms.py?

Thank you very much.

Best,
Satomi

**Comment by christopher-vollmers** [comment]
How short are the reads (median) and how does relate to the size of the
cDNA on a gel?
As far as I know, LAST is really good at aligning noisy reads but does not
handle splicing at all so you will get multiple alignments for each read
(basically one for each exon). So I would recommend against using it.

**Comment by satomimitsuhashi** [comment]
Median read length was 1349bp.
I did not check the size in detail but the peak was more than 3kb on a gel.

I think last can detect splicing now, but if you do not recommend, I would like to try blat then.
Can I run Mandalorion by replacing the blat .psl file with the gmap .psl?

Thank you very much,

Best,
Satomi

**Comment by christopher-vollmers** [comment]
You are right. LAST might just work. If you have the psl you can simply
change the name to "2D_trimmed_l_gmapoutput.psl" and rerun Mandalorian_4
but comment out the alignment step (line 106).

Let me know whether that works for you.

**Comment by satomimitsuhashi** [comment]
Thank you very much! That was very helpful.
I will let you know how it works.

Best,
Satomi

**Comment by satomimitsuhashi** [comment]
Dear Chris,

I tried this, 

>  If you have the psl you can simply
> change the name to "2D_trimmed_l_gmapoutput.psl" and rerun Mandalorian_4
> but comment out the alignment step (line 106).

but, 2D_trimmed_l_filtered.fasta still remained empty. 
And it produced these error messages.

I hope you could help me again...

$ python3 Mandalorion_define_and_quantify_isoforms.py -c ./content_file -p ./output/ -a genes.gtf -g GRCh37 -l gene_list.txt
.//2D_trimmed_l_gmapoutput_filtered.psl	.//2D_trimmed_l_filtered.fasta	.//
Traceback (most recent call last):
  File "Mandalorion_5_TESS.py", line 414, in <module>
    histo_left_bases, histo_right_bases,chromosome_list,histo_coverage=collect_reads(content_file)
  File "Mandalorion_5_TESS.py", line 73, in collect_reads
    seq=read_seq[name]
KeyError: '180ccd1d-3748-49db-91a6-435bb7bf0a22'
.//2D_trimmed_l_gmapoutput_filtered.psl	.//2D_trimmed_l_filtered.fasta	.//
Traceback (most recent call last):
  File "Mandalorion_6_SS.py", line 506, in <module>
    histo_left_bases, histo_right_bases,chromosome_list,histo_coverage=collect_reads(content_file)
  File "Mandalorion_6_SS.py", line 260, in collect_reads
    seq=read_seq[name]
KeyError: '180ccd1d-3748-49db-91a6-435bb7bf0a22'
Traceback (most recent call last):
  File "Mandalorion_define_and_quantify_isoforms.py", line 27, in <module>
    if 'i' in refine:
TypeError: argument of type 'NoneType' is not iterable


Best,
Satomi
