### ISSUE TITLE
Error when running `Mandalorion_just_align.py`

### ISSUE THREAD

**Issue by kmnip** [christopher-vollmers/Mandalorion-old#11]
I got this error when running the script on the ONT reads from the paper:

```
Traceback (most recent call last):
  File "Mandalorion_3_Remove_ISPCR_Sequences.py", line 109, in <module>
    find_ispcr(path+'/'+input1)
  File "Mandalorion_3_Remove_ISPCR_Sequences.py", line 52, in find_ispcr
    reverse_b=reverse_complement(b)
  File "Mandalorion_3_Remove_ISPCR_Sequences.py", line 25, in reverse_complement
    Seq=Seq+complement[item]
KeyError: '3'
```
The script continued to run, but I am not sure whether the results are correct and complete. Please fix this.

Thanks!

**Comment by mmilevskiy** [comment]
I too am seeing this error. The output files are empty, except for the 2D.fastq. So I don't think anything has happened with the data. Any help on this thread is much appreciated.

**Comment by davidwumdphd** [comment]
I get this error as well. Any help?
